apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: default
spec:
  provider:
    vault:
      caProvider:
        key: ca.crt
        name: vault-tls
        namespace: vault
        type: Secret
      auth:
        kubernetes:
          mountPath: kubernetes
          role: karavel
          serviceAccountRef:
            name: external-secrets-default-store
            namespace: external-secrets
      path: secret
      server: https://vault.vault.svc.cluster.local:8200
      version: v2
